// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl_ZBVrj8mYWjr2hO8cphv5UI79kNDzgM',
    appId: '1:1026468191696:web:4719f8e4abd243eaadadd5',
    messagingSenderId: '1026468191696',
    projectId: 'syn-5bf5a',
    authDomain: 'syn-5bf5a.firebaseapp.com',
    storageBucket: 'syn-5bf5a.firebasestorage.app',
    measurementId: 'G-CVNP96CBWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDynzkQ_w9U1XICIJhAG8bZn8xkbiBe9dY',
    appId: '1:1026468191696:android:5aeac9e638ad97caadadd5',
    messagingSenderId: '1026468191696',
    projectId: 'syn-5bf5a',
    storageBucket: 'syn-5bf5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjh8p5kgqqzbAbVaV0v44egwrHnhm3OCg',
    appId: '1:1026468191696:ios:37d36c218f5c857aadadd5',
    messagingSenderId: '1026468191696',
    projectId: 'syn-5bf5a',
    storageBucket: 'syn-5bf5a.firebasestorage.app',
    iosBundleId: 'com.example.syn',
  );
}
